### ISSUE TITLE
Integration does not recongize LUBA1 starting from 0.1.12

### ISSUE THREAD

**Issue by sgurgul** [mikey0000/Mammotion-HA#100]
### The problem

I have LUBA 1. 
Integration works very well until version 0.1.11.

Using two recent versions (0.1.12 and 0.1.13) the device is not recognized properly - all entities remain unvailable.
Downgrading to 0.1.11 restores the functionality.

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.11

### What version of Home Assistant Core are you running?

2024.8.3

**Comment by hauseroliver** [comment]
Same here with Luba 2.

**Comment by ThorstenBoettler** [comment]
Same here with Luba 2

**Comment by mikey0000** [comment]
please update to 0.1.14 fixes issue with the integration not starting properly sometimes.
