### ISSUE TITLE
Luba LED switch inverted

### ISSUE THREAD

**Issue by tiefflieger666** [mikey0000/Mammotion-HA#117]
### The problem

The switch is inverted - in HA ON -> real OFF and vs 

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.21

### What version of Home Assistant Core are you running?

 core-2024.9.1

**Comment by tiefflieger666** [comment]
Addition:
It looks like it's interfering "wrong" with the Mammotion app - I'm unable to turn on the LED via the integration or the Mammotion app. The switch in the app is switching, but the LED does not turn on.

**Comment by mikey0000** [comment]
It only shows while mowing

**Comment by mikey0000** [comment]
> Addition: It looks like it's interfering "wrong" with the Mammotion app - I'm unable to turn on the LED via the integration or the Mammotion app. The switch in the app is switching, but the LED does not turn on.

Two things, make sure your using a different account on HA vs your mobile app, secondly the command is identical to the mammotion app, it does not interfere.

**Comment by tiefflieger666** [comment]
My mistake - working (overseen that at some point they changed that the led is only on when moving). 

Sorry.

But still inverted.

**Comment by mikey0000** [comment]
Pretty sure I've fixed it in 0.1.25, give it a go.

**Comment by tiefflieger666** [comment]
Hi. 

thx - with 0.1.26 the led issue is solved (correct state). But an ugly lag in the communication between Luba / app and HA implemented - but I'm quite sure that this will solved.

thx for that great integration.

**Comment by mikey0000** [comment]
Yeah the way MQTT and how they've implemented it in the app really. Not a whole lot I can do about it, however lots of improvements to come.
