### ISSUE TITLE
unclear installation instruction

### ISSUE THREAD

**Issue by mibr85** [mikey0000/Mammotion-HA#118]
### The problem

I looking for:
Open the Home Assistant web interface.
2. Navigate to "Configuration" > "Integrations". 
But I can't find "Configurations" on the web interface?

<img width="1710" alt="Bildschirmfoto 2024-09-11 um 08 12 10" src="https://github.com/user-attachments/assets/b3dfee3f-5abb-4cec-8cc4-eaa4fe85e57d">

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

latest

### What version of Home Assistant Core are you running?

core-2024.9.1

**Comment by mikey0000** [comment]
Devices and Services -> +

**Comment by mikey0000** [comment]
Can you please point me to where you read this instruction so I can make it clearer?

**Comment by mibr85** [comment]
was my fault, I missed the first line: "This integration can be installed using [HACS](https://hacs.xyz/)"
<img width="856" alt="Bildschirmfoto 2024-09-11 um 14 39 53" src="https://github.com/user-attachments/assets/e5226391-6d12-4a84-98cf-ac672085adfe">

**Comment by mibr85** [comment]
Error show up:
<img width="481" alt="Bildschirmfoto 2024-09-11 um 14 53 12" src="https://github.com/user-attachments/assets/40cf48a7-b420-475e-9a3a-b63d67e09480">

**Comment by mikey0000** [comment]
You probably added it already, proceed to the next step
