### ISSUE TITLE
Nudge-Buttons don't work

### ISSUE THREAD

**Issue by Sergey842248** [mikey0000/Mammotion-HA#119]
### The problem

If I press on the Nudge-Buttons, for example if i press the "Emergency nudge forward"-Button nothing happens, only the state of the entity changes but my Luba don't drive in any direction. 
May I'm doing anything wrong?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.24

### What version of Home Assistant Core are you running?

	core-2024.9.1

**Comment by mikey0000** [comment]
Bluetooth only for now.

**Comment by Sergey842248** [comment]
Thanks!
