### ISSUE TITLE
I used the Blade spinning switch and now he is no longer starting to mow?

### ISSUE THREAD

**Issue by Pino72de** [mikey0000/Mammotion-HA#120]
### The problem

Hi,
 
installed the latest Version on HA and created a separate account.

I tried some switches and also the spin blades switch...it works but since I used it Yuka will start a new mowing task and drive to starting point but then stands there without spinnig the blades...he then reports stuck blades which is not true. If I activate the blade through HA it starts the mowing task...but he never stops the blades...even when docked and charging!

How can I restore "normal" behaviour? Do I need to reset the Yuka in some way for it to function normally again?

Thanks

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.1.24

### What version of Home Assistant Core are you running?

core-2024.9.1

**Comment by mikey0000** [comment]
So that button should only be used when your mower is already travelling to mow or stops during a mow, someone else had this issue, the only solution is to turn the mower off and on again. In future I'll look at a way around this problem. But it is a bug in the firmware.
