### ISSUE TITLE
Logout from Mammotion app and programmed tasks not visible

### ISSUE THREAD

**Issue by Shogun1978** [mikey0000/Mammotion-HA#128]
### The problem

Hello,

I waited for the initial wi-fi release because I don't use the BLE proxy (range is too short and I have wi-fi in my garden).
When I configure the Mammotion integration, I will be locked out with the app. Seems like the Mammotion API accepts just one active login. Maybe there is a workaround possible.
The second "issue" (more a RFE) is that I don't see programmed tasks. It would be great to see the already configured areas and the connected tasks to that area. If the ones configured areas and scheduled tasks could be triggered from HA, there would be no need to access the Mammotion app (at least until there are issues or updates for the robot).
If there is anything I can test, I am happy to do so.

Regards,
Harald

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.34

### What version of Home Assistant Core are you running?

2024.8.3

**Comment by mibr85** [comment]
Hi Harald
as i know you need to make a second account and share your Luba with this account, log in with the new account in the app, accept the shared Luba, than you can use the second account at HA and the first account with your App.

**Comment by mibr85** [comment]
Task and schedules atr on the roadmap:
![image](https://github.com/user-attachments/assets/fd8540d8-8223-472e-a0b3-7f079fde5e4e)

**Comment by Shogun1978** [comment]
> Hi Harald as i know you need to make a second account and share your Luba with this account, log in with the new account in the app, accept the shared Luba, than you can use the second account at HA and the first account with your App.

Thanks for the fast reply! I will try that and watch out for and updates. If I can support with testing some features or function, I am happy to do so.

**Comment by mibr85** [comment]
you can close the issue?

**Comment by nijel** [comment]
Everybody using this integration has learned that, but there is no mention of this in the documentation, so new users have no chance to know that before hitting issues like described here. Mentioning this in the README would be great, having it documented in the setup wizard would be even better.

**Comment by mibr85** [comment]
@nijel i fully agree with you
