### ISSUE TITLE
No WIFI or BLE decision is ask during config wizard 

### ISSUE THREAD

**Issue by mibr85** [mikey0000/Mammotion-HA#129]
### The problem

I just add my LUBA 2 and after add my credentials there was no choice to decide, if i like to use WIFI or BLE, do i need to be connected with BLE during setup?
but I can see all datas in HA.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.34

### What version of Home Assistant Core are you running?

core-2024.9.1

**Comment by mikey0000** [comment]
Yes you can decide, by ticking or unticking the use WiFi box, you can also later change it by hitting reconfigure

16/09/2024 10:39:06 pm mibr85 ***@***.***>:
