### ISSUE TITLE
integreat the need of an seperate account to the installation instruction and the wizard

### ISSUE THREAD

**Issue by mibr85** [mikey0000/Mammotion-HA#130]
### The problem

When you don't like to be locked out in your App, you need to make a second account and share your Luba with this account, log in with the new account in the app, accept the shared Luba, than you can use the second account at HA and the first account with your App.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.34

### What version of Home Assistant Core are you running?

v0.1.34

**Comment by mikey0000** [comment]
Done
