### ISSUE TITLE
no Area switch

### ISSUE THREAD

**Issue by Striker2102** [mikey0000/Mammotion-HA#138]
### The problem

Hello,

First of all, thank you for this great work!

When I click on "Sync with Map," no areas are created anymore. I have already removed and re-added the Luba. Is there a trick to getting the area switches?

i have 3 areas in the Mammontion app configured

Thank you very much!

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.39

### What version of Home Assistant Core are you running?

2024.09.01

**Comment by mikey0000** [comment]
I've diagnosed a small issue which I'm working on. Might resolve your issues.

20/09/2024 10:07:18 am Striker2102 ***@***.***>:

**Comment by Striker2102** [comment]
Hello,

Area 1 comes back but i missing the other areas

![image](https://github.com/user-attachments/assets/a9969daa-44e1-4200-871d-16f90acddea3)

i have also reload the integration, then is the area 1 unavailable again
![image](https://github.com/user-attachments/assets/65c02916-daa5-49c1-b623-a4cc26d71af0)

after delete the luba and sync maps again, no areas are created anymore :-(

![image](https://github.com/user-attachments/assets/9cef16fb-1235-430e-9647-3d58d637af4f)


thank you

**Comment by mikey0000** [comment]
Hold tight I have a fix coming.

If you reload (assuming you don't do it immediately after sync maps) your area should restore, if not hit the sync maps button again.

20/09/2024 9:07:42 pm Striker2102 ***@***.***>:

**Comment by Striker2102** [comment]
Thank you its work now with Release v0.1.43
