### ISSUE TITLE
Update broke integration

### ISSUE THREAD

**Issue by sidsolutions-net** [mikey0000/Mammotion-HA#139]
### The problem

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 7:52:47 PM (1 occurrences)
Last logged: 7:52:47 PM

Error setting up entry Yuka-YVJWJAA8 for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 114, in async_setup
    device = self.manager.get_device_by_name(self.device_name)
                                             ^^^^^^^^^^^^^^^^
AttributeError: 'MammotionDataUpdateCoordinator' object has no attribute 'device_name

Failed to set up:
Check the log

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.1.39

### What version of Home Assistant Core are you running?

Core-2024.9.2

**Comment by mikey0000** [comment]
try 0.1.42 out now.

**Comment by mikey0000** [comment]
Closing as haven't gotten a reply
