### ISSUE TITLE
Error calling the lawn_mower/start_mowing service. Unreachable

### ISSUE THREAD

**Issue by markuslaube** [mikey0000/Mammotion-HA#14]
Hello,

first of all, thank you for you amazing work so far 💙

second of all I don't have a Luba but the YUKA, the integration works great for me first of all with regard to the sensors using the BLE proxy. I get a total of 14 entities, all of which provide a meaningful value. Or actually 13, one value is not useful insofar as the YUKA cannot know which blade height is set, where it delivers a constant 50mm.

However, when I want to send actions, I get errors:

Start:
Error calling the lawn_mower/start_mowing service. Unreachable
Orignial "Fehler beim Aufrufen des Diensts lawn_mower/start_mowing. Unreachable"

Pause:
Error when calling the service lawn_mower/pause. Unreachable

Back to
Currently no message - but is ignored

Do you have any idea where I should look, does anyone have the same problem with the Luba or Luba2 or do I have to put in more work to adapt it to the Yuka?

Thank you!

**Comment by markuslaube** [comment]
Arghh: 

2024-06-18 16:19:03.905 WARNING (MainThread) [custom_components.localtuya.common] [bfa...vns] Failed to connect to 172.16.2.114: [Errno 113] Connect call failed ('172.16.2.114', 6668)
2024-06-18 16:19:26.689 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547127100896] Unexpected exception

I'm afraid Mammotion has done something different again. Is there any experience whether the Luba2 works with the integration? My nmap actually doesn't see any open ports despite the fact that the Yuka can be reached via ping and controlled via app.

**Comment by mikey0000** [comment]
This integration is under heavy development, I'll try and see what's going on today. This integration currently only works over Bluetooth(WiFi being worked on) , there is also currently an issue where sometimes connecting doesn't work as expected. As for the mow actions, they should be working, something must have broken recently.

Thanks for letting us know that Yuka doesn't have an adjustable blade height?

**Comment by markuslaube** [comment]
Yes, the height adjustment on the YUKA is exclusively manual with a mechanical knob.

**Comment by markuslaube** [comment]
If you need more information, logs, etc.: let me know - anytime!
Markus

**Comment by mikey0000** [comment]
So, in short none of the devs working on this have a Yuka, however we have someone who will be able to loan one to us in the future. the unreachable message is a bit misleading and I need to change it, it means one of two things, bluetooth connection wasn't able to be made or an error occurred in sending the command (or command was wrong).

**Comment by rasssta** [comment]
Just to add some info to the mechanical knob. It has 8 different settings: 2, 3, 4, 5, 6, 7, 8, 9 (cm). Not sure if this is going to be reflected in the robot communication somehow. But now you know :)

**Comment by rasssta** [comment]
Can't find it in the app

**Comment by rdone2018** [comment]
Hello, same error "Unreachable"
Device Mammotion Luba 2

This error originated from a custom integration.

Logger: custom_components.mammotion
Source: helpers/update_coordinator.py:312
integration: Mammotion
First occurred: June 27, 2024 at 2:42:50 PM (94 occurrences)
Last logged: 5:57:11 AM

Unexpected error fetching Mammotion Lawn Mower data data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 57, in _async_update_data
    return await self.device.start_sync(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 201, in start_sync
    plan = await self._send_command_with_args("read_plan", **{'id': 2})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 267, in _send_command_with_args
    raise RuntimeError("Unreachable")
RuntimeError: Unreachable

**Comment by rdone2018** [comment]
I think, I have last release (installed only on yesterday)

**Comment by rdone2018** [comment]
I did update of custom component now. 
 Now I cannot connect to Luba - not even static data as before.

Logger: custom_components.mammotion
Source: helpers/update_coordinator.py:312
integration: Mammotion
First occurred: 7:04:38 AM (12 occurrences)
Last logged: 7:18:35 AM

Unexpected error fetching Mammotion Lawn Mower data data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 57, in _async_update_data
    return await self.device.start_sync(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 201, in start_sync
    plan = await self._send_command_with_args("read_plan", **{'id': 2})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyluba/mammotion/devices/luba.py", line 267, in _send_command_with_args
    raise RuntimeError("Unreachable")
RuntimeError: Unreachable

**Comment by rdone2018** [comment]
Deleted device + restart HA - helps 
Same status as yesterday - data visible, commands not working

**Comment by lackr007** [comment]
I can confirm the same error "Unreachable" for all commands (Go/Pause/Dock/Resume Mowing) for Luba 2. Thanks for all the work on this!

**Comment by mikey0000** [comment]
Resolved. Please open a new ticket if your still encountering this.
