### ISSUE TITLE
Values in HA not updating

### ISSUE THREAD

**Issue by mibr85** [mikey0000/Mammotion-HA#143]
### The problem

The value HA Mammotion integration do not update, they updates only during setup.
Will they update automatically or do i need to pull them anyhow?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.43

### What version of Home Assistant Core are you running?

v0.1.34

**Comment by mikey0000** [comment]
Are you using a second account? Check your logs.

**Comment by mibr85** [comment]
yes i do have a second account

which part of log?

**Comment by mikey0000** [comment]
Well turn on debugging and wait about 5 minutes and then turn it off, it will give you a log file

**Comment by mibr85** [comment]
I know how to get the file size is 24MB should I share this file here?

**Comment by mikey0000** [comment]
Got discord? Can pm me on there

**Comment by trentjw** [comment]
mine does not update either and if I do a reload it fails

**Comment by mibr85** [comment]
same here with 0.1.45

**Comment by mikey0000** [comment]
please try 0.1.55

**Comment by ysoudy** [comment]
Same here.. i have no update on my Yuka since yesterday

**Comment by mikey0000** [comment]
Being tracked in #152
