### ISSUE TITLE
Google Authentication instead of username/password

### ISSUE THREAD

**Issue by pascalkocher** [mikey0000/Mammotion-HA#146]
### The problem

The integration works with the username/password pair from the Mammotion App.
If a user uses  his Google Account to connect to Mammotion, there is no way to set a password for the integration.
Adding Google Auth for the integration would solve this issue.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

latest

### What version of Home Assistant Core are you running?

core-2024.9.2

**Comment by mikey0000** [comment]
Considering you need to create a second account specifically for home assistant, to use with this integration, I'm going to close this as a won't fix. Your main account might be Google but your secondary account can be a normal email and password.
