### ISSUE TITLE
After reinstalling Integration 'Device is already configured'

### ISSUE THREAD

**Issue by tgessendorfer** [mikey0000/Mammotion-HA#149]
### The problem

I had to uninstall and reinstall the Mammotion integration and sadly can't add my Luba anymore getting the error message 'device is already configured' after reinstall trying to add my Luba account.

I get the drop-down menu listing my Luba mower but when adding it the error occurs.

![Screenshot_20240923-205400](https://github.com/user-attachments/assets/92abef66-e51e-4251-987a-7b7ac2863644)

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.45

### What version of Home Assistant Core are you running?

core-2024.9.2

**Comment by mikey0000** [comment]
Can you take some logs for me please and also tell me if you are using Bluetooth and or wifi

**Comment by tgessendorfer** [comment]
> Can you take some logs for me please and also tell me if you are using Bluetooth and or wifi

How can I figure out if I use Bluetooth or Wifi when configuring the integration?

**Comment by tgessendorfer** [comment]
could fix it by myself... seems that uninstallation of the integration/repo does leave some Mammotion device artifacts back in **_config/.storage/core.config_entries_**.
So had to delete those and restart Homeassistant. Then readding the integration and running the configuration works.

Find your entry with:
`grep -B 10 -A 20 mammotion config/.storage/core.config_entries`

Delete all the artifacts and restart homeassistant...
