### ISSUE TITLE
BLE RSSI reading 0

### ISSUE THREAD

**Issue by romeoechovictor** [mikey0000/Mammotion-HA#15]
Absolutely amazing so far, thank you so much.

Just one thing I noticed was the BLE RSSI is mainly reading zero.  Sometimes it does read correctly, but overall it reads zero.  I'll attach a screenshot of the wifi & bt history graph.  There is data being sent all the time through the BT proxies (you can see the wi-fi rssi data on the graph is consistent).

Any other information I can supply please let me know.

![image](https://github.com/mikey0000/HA-Luba/assets/20481726/7582b195-df97-4c87-b925-b1dc1c3997db)

**Comment by romeoechovictor** [comment]
> How many BT Proxies are you using?

3, if you like I can drop to just 1 but it will only then receive bluetooth when the luba is near the docking station.

**Comment by romeoechovictor** [comment]
You can see the graph here showing the wifi rssi and BT rssi while it's docked.  It hasn't moved and would be only coming through on a single proxy at this time.  The BT RSSI only intermittently outputs an actual value (circled in red) the majority of the time it's sending 0.  The purple graph shows the wifi rssi 

It doesn't drop per say, it sends a zero as the BT rssi.

![image](https://github.com/mikey0000/HA-Luba/assets/20481726/6cf78926-539e-4703-ad6f-b4726180fb83)

**Comment by romeoechovictor** [comment]
That might work, but so long as it doesn't join up the values on the HA graphs?  
Unless it only transmits then if the rssi level changes? (but the levels don't seem that flat)

This evening the only captured ble_rssi were at:

22:58, 22:47, 22:37, 21:27, 21:12, 21:01, 20:30, 19:52, 19:07, 18:34, 18:27

I don't see much of a pattern.  How often is it updating for the rest of you?
The other data seems to update itself at differing intervals depending on the frequency of changing.

So the most updates are coming from WiFi RSSI, Satellites and L2 & L1 Satellites (Co-Viewing)

**Comment by mikey0000** [comment]
Is this still an issue now?

**Comment by TTLucian** [comment]
Same problem here with Yuka robot.

**Comment by romeoechovictor** [comment]
I think I had a look at the raw data being received via bt. Looks like the data itself is zero so it's not the hass integration itself, looks like the data is actually sending zero to the hass integration. Is this correct? Not sure how you'd fix this if that's the case.  Perhaps just don't report or display 0 value as 0 would be a massively strong and therefore unlikely rssi to be received.

**Comment by mikey0000** [comment]
So ble RSSI if your not connected over bluetooth will come back as zero and this is normal
