### ISSUE TITLE
0.1.45 Only 3 of 7 areas are being shown in the configuration - can see them in the json

### ISSUE THREAD

**Issue by hoontune** [mikey0000/Mammotion-HA#150]
### The problem

Thanks for all your work, hoping this might help you debug the area stuff.

I can see the following areas in the JSON

`     "area_name": [
        {
          "name": "ShaneFence",
          "hash": 529223445277635707
        },
        {
          "name": "Patio",
          "hash": 1710370417204241082
        },
        {
          "name": "TopYard-FirepitSide",
          "hash": 3029222843701709254
        },
        {
          "name": "LowerYard",
          "hash": 4256756928992369879
        },
        {
          "name": "EmmaParkingArea",
          "hash": 5007095678149156872
        },
        {
          "name": "Gate",
          "hash": 6702000680844874001
        },
        {
          "name": "DaveFence",
          "hash": 7998305658913381015
        }
      ]
`

Only the following appear under configuration:
DaveFence
Gate
TopYard-FirepitSide

I have tried to re-sync a few times over the course of a few hours but it doesn't seem to add any more.

[config_entry-mammotion-01J8CAXZC64FH891SEWV9531GZ (1).json](https://github.com/user-attachments/files/17105901/config_entry-mammotion-01J8CAXZC64FH891SEWV9531GZ.1.json)

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.45

### What version of Home Assistant Core are you running?

core-2024.8.1

**Comment by ClockeNessMnstr** [comment]
0.1.43+ send to have an issue loading for me as well. 

0.1.42 and earlier should work better

**Comment by J-Lindvig** [comment]
First of all - thank you for a much needed integration.

I am also not receiving all areas.

`      "area_name": [
        {
          "name": "Lille sandkasse",
          "hash": 1080696295809225835
        },
        {
          "name": "Hjalte",
          "hash": 1458239989606767672
        },
        {
          "name": "Hj\u00f8rnet",
          "hash": 2784920174772637982
        },
        {
          "name": "Bakken",
          "hash": 4407870666210035191
        },
        {
          "name": "Sandkassen",
          "hash": 5454054011133281379
        },
        {
          "name": "Hegnet",
          "hash": 5776043850686961937
        },
        {
          "name": "Tennisklubben",
          "hash": 7327013264565088048
        },
        {
          "name": "Skuret",
          "hash": 8312470430197850595
        },
        {
          "name": "Foran",
          "hash": 9041177338583610365
        }
      ]`
      
I only have 4 areas in my configured unit.
![Screenshot 2024-09-25 10 15 43](https://github.com/user-attachments/assets/723d708b-cbe8-4c77-a3ca-5431a58109d6)

**Comment by mikey0000** [comment]
should be fixed now.

**Comment by ClockeNessMnstr** [comment]
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:761
integration: Switch (documentation, issues)
First occurred: 11:53:05 AM (5 occurrences)
Last logged: 11:53:50 AM

Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_492618846148179789 already exists - ignoring switch.luba_vs734gny_corner
Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_1651405550032429529 already exists - ignoring switch.luba_vs734gny_boulevard
Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_7262803619377414321 already exists - ignoring switch.luba_vs734gny_side_yard
Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_2504906330228778575 already exists - ignoring switch.luba_vs734gny_front_yard
Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_9162803946157057577 already exists - ignoring switch.luba_vs734gny_backyard

After last update I'm getting this. 
Everything looks ok so far but not sure if this will trip it up after editing the zone or something.

**Comment by mikey0000** [comment]
> Logger: homeassistant.components.switch Source: helpers/entity_platform.py:761 integration: Switch (documentation, issues) First occurred: 11:53:05 AM (5 occurrences) Last logged: 11:53:50 AM
> 
> Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_492618846148179789 already exists - ignoring switch.luba_vs734gny_corner Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_1651405550032429529 already exists - ignoring switch.luba_vs734gny_boulevard Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_7262803619377414321 already exists - ignoring switch.luba_vs734gny_side_yard Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_2504906330228778575 already exists - ignoring switch.luba_vs734gny_front_yard Platform mammotion does not generate unique IDs. ID Luba-VS734GNY_9162803946157057577 already exists - ignoring switch.luba_vs734gny_backyard
> 
> After last update I'm getting this. Everything looks ok so far but not sure if this will trip it up after editing the zone or something.

Yeah I'm running into this as well, it's not filtering properly before trying to add, it's not going to cause any problems but I do need to address it.

**Comment by mikey0000** [comment]
Should be resolved now.
