### ISSUE TITLE
Second Account?

### ISSUE THREAD

**Issue by trentjw** [mikey0000/Mammotion-HA#151]
### The problem

you have this in your instructions "Second account with your mower shared to it for using Wi-Fi (If you use your primary it will log you out of your mobile app)"

Mamotion does not allow the mower to be shared between two accounts so, Step by step intructions on getting the LUBA shared to a second account would probably go along ways 

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

unsure

### What version of Home Assistant Core are you running?

core-2024.9.2

**Comment by mikey0000** [comment]
They specifically have 
![Screenshot_20240924-151645](https://github.com/user-attachments/assets/b450f3fc-0c46-47f4-84bf-2a676a2fbb3c)

You need to create a brand new second account and share to it.

**Comment by mikey0000** [comment]
Yes could make the instructions clearer, will get to it eventually.
