### ISSUE TITLE
integration polling interval apparently cannot be disabled

### ISSUE THREAD

**Issue by fschaer** [mikey0000/Mammotion-HA#153]
### The problem

Hi

this is probably related to #142 : I tried to disable the integration polling interval in home assistant, for my luba2 instance.

My aim is to disable the charging station (and polling) when battery reaches 80%, then re-enable all this when the luba leaves the station of falls below X percent (maybe polling once per hour, or per 2 hours of whatever)

Home assistant states polling interface is actually disabled when looking at the mammotion integration => luba => system settings => "enable polling" disabled. However : 
- battery drain on the luba seems to persist
- battery percentage in the integration is actually updated without having anything in place in any automation to trigger an instance update

This makes me think the integration is still polling the luba, and it never sleeps :/

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.45

### What version of Home Assistant Core are you running?

core-2024.9.2

**Comment by mikey0000** [comment]
Added switch in 0.1.58

**Comment by elmr91** [comment]
V 0.1.66 has fix for this 
Please refer to  #142
