### ISSUE TITLE
Error writing config for XXXX: Failed to serialize to JSON

### ISSUE THREAD

**Issue by tomcsi** [mikey0000/Mammotion-HA#154]
### The problem

Hello,

I have two Luba 2 in the HA, and since yesterday I get this error message:
```
Logger: homeassistant.helpers.storage
Source: helpers/storage.py:542
First occurred: 18:05:28 (5 occurrences)
Last logged: 18:11:17

Error writing config for Luba-VSEERWL4: Failed to serialize to JSON: /config/.storage/Luba-VSEERWL4. Bad data at $.data.device.sys.todev_off_chip_flash.data=b''(<class 'bytes'>, $.data.device.sys.toapp_lora_cfg_rsp.fac_cfg=b''(<class 'bytes'>
```

I checked, the file that finding not in the directory. What do I need to do to create this file?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.45

### What version of Home Assistant Core are you running?

core-2024.9.2

**Comment by tomcsi** [comment]
If I copy another luba file to this location, that it's work fine (it seems)

**Comment by mikey0000** [comment]
There is some data it's unable to save to file. I'll investigate

**Comment by mikey0000** [comment]
should be fixed in latest
