### ISSUE TITLE
the grass abeging module turned on, when starting yuka

### ISSUE THREAD

**Issue by nieand1985** [mikey0000/Mammotion-HA#157]
### The problem

Hello, first of all, thank you very much for your great work. :-)
 
I have been using the Mammotion in Homeassitent for about two months and have the following problem. As soon as I press the start button, I get an error message saying the Grass Abeging Module was not recognized and the Yuka will not start. This message only appears in the Mammotion app and not in Home Assistant. If I then open the official Mammotion app, the module is also activated there.

I have not installed this module on the Yuka either.

Do you have a solution for me?

Many thanks in advance

Greetings nieand

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

V0.1.45

### What version of Home Assistant Core are you running?

core-2024.9.3

**Comment by mikey0000** [comment]
Can you please try newest release

**Comment by nieand1985** [comment]
I have now installed version 0.1.50, but unfortunately, the issue still persists. However, I found out that the error no longer appears, and Yuka resumes its work when I toggle the "Collect grass" switch on and off.

However, when I reload the Mammotion integration, the error reappears. Only toggling the switch again resolves the problem.

It seems like the switch is active, even though it is displayed as "off" in Home Assistant.

**Comment by mikey0000** [comment]
Cool I'll check that out, it's supposed to determine this automatically based on if the collector is attached or not.

**Comment by nieand1985** [comment]
Hello again, I have another piece of information that I would like to share. I have installed a second battery in my Yuka so that it simply mows for longer. Perhaps this has something to do with the automatic detection of the collector? 

greetings nieand

**Comment by mikey0000** [comment]
> Hello again, I have another piece of information that I would like to share. I have installed a second battery in my Yuka so that it simply mows for longer. Perhaps this has something to do with the automatic detection of the collector?
> 
> greetings nieand

Not sure but if you create a saved service call and turn off the mowing collection and so on, does it start the mow?

**Comment by nieand1985** [comment]
In the Mammotion app, the “Grass Collection” switch is disabled. When I start the mower using this app, the switch remains disabled, and the Yuka begins its work as it should.

However, when I start it through Home Assistant, the “Grass Collection” switch is also disabled there. But as soon as I press the “Mow” function, the Mammotion app shows the error: “Grass module not detected,” and the “Grass Collection” switch is activated in the Mammotion app, even though it remains disabled in Home Assistant.

If I then disable the switch in the Mammotion app and press the “Mow” button again in Home Assistant, the switch in the Mammotion app is reactivated. Only when I toggle the switch in Home Assistant (turn it on and off again) and then press “Mow” does the mower start and begin mowing. (I suspect the switch is being activated in the background.)

If you have any further questions, feel free to reach out. I hope this helps.

Best regards,
Nieand

**Comment by mikey0000** [comment]
if you turn on debugging and look for the big data dump, look for `collector_installation_status` and report it back to me please

**Comment by mikey0000** [comment]
Actual state should now be reflected in the newest version.

**Comment by nieand1985** [comment]
I have copied and pasted a few logs for you, I hope I have found the right information, Home Assistant is a completely new country for me 
😅 

Logger: homeassistant.components.switch
Quelle: helpers/entity_platform.py:761
Integration: Schalter (Dokumentation, Probleme)
Erstmals aufgetreten: 09:19:34 (6 Vorkommnisse)
Zuletzt protokolliert: 09:21:41

Platform mammotion does not generate unique IDs. ID Yuka-YVA35SSB_7408579010946054535 already exists - ignoring switch.yuka_yva35ssb_area_4
Platform mammotion does not generate unique IDs. ID Yuka-YVA35SSB_6613924448326214871 already exists - ignoring switch.yuka_yva35ssb_3
Platform mammotion does not generate unique IDs. ID Yuka-YVA35SSB_6604775417495041071 already exists - ignoring switch.yuka_yva35ssb_area_4_2
Platform mammotion does not generate unique IDs. ID Yuka-YVA35SSB_7720054949041122863 already exists - ignoring switch.yuka_yva35ssb_2
Platform mammotion does not generate unique IDs. ID Yuka-YVA35SSB_5994799645292326317 already exists - ignoring switch.yuka_yva35ssb
 

Another logs: 


Logger: homeassistant
Quelle: /usr/src/homeassistant/homeassistant/runner.py:147
Erstmals aufgetreten: 13:38:32 (1 Vorkommnisse)
Zuletzt protokolliert: 13:38:32

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "<string>", line 92, in __mashumaro_from_dict__
  File "<string>", line 5, in __unpack_literal_DeviceNotificationEventParams_identifier__bbfbbce10dad4e169f2b9f3211a0dcdf
ValueError: device_warning_code_event

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 116, in _on_mqtt_message
    await self._handle_mqtt_message(topic, payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 137, in _handle_mqtt_message
    await self._parse_mqtt_response(topic=topic, payload=payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 122, in _parse_mqtt_response
    event = ThingEventMessage.from_dicts(payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/data/mqtt/event.py", line 158, in from_dicts
    params_obj = DeviceNotificationEventParams.from_dict(params_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 94, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "identifier" of type Literal['device_notification_event'] in DeviceNotificationEventParams has invalid value 'device_warning_code_event'



And another logs:


Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mammotion
Quelle: helpers/update_coordinator.py:354
Integration: Mammotion (Dokumentation, Probleme)
Erstmals aufgetreten: 15:08:56 (1 Vorkommnisse)
Zuletzt protokolliert: 15:08:56

Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 470, in _async_update_data
    await self.async_send_command("get_device_product_model")
  File "/config/custom_components/mammotion/coordinator.py", line 100, in async_send_command
    await self.manager.send_command_with_args(
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 277, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/base.py", line 235, in command
    return await self.queue_command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 231, in queue_command
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 80, in process_queue
    result = await self._execute_command_locked(iot_id, key, command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 96, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 681, in send_cloud_command
    response = client.do_request("/thing/service/invoke", "https", "POST", None, body, RuntimeOptions())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alibabacloud_iot_api_gateway/client.py", line 132, in do_request
    raise UnretryableException(_last_request, _last_exception)
Tea.exceptions.UnretryableException: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by mikey0000** [comment]
Can you update to 0.1.59 please

**Comment by mikey0000** [comment]
Then you should see the grass collection switch is turned on, switch it off before starting a mow

**Comment by nieand1985** [comment]
Hey I have installed version v0.1.59 and now it seems to work.👍🏻
Will try it again with different scenarios. 

Thank you very much for the help

**Comment by mikey0000** [comment]
Awesome

**Comment by mikey0000** [comment]
0.1.65 now sets the blade height to what yuka is expecting so should work better now

**Comment by nieand1985** [comment]
Good evening, I apologize for only getting back to you now. So with the latest version (Mammotion integration)
the switch for collecting grass is displayed correctly. In my case, the switch is set after a restart of Home Assistant, although I have not installed a grass collection module...but that's not a problem, I simply deactivate it.

Many thanks for your help
