### ISSUE TITLE
No access to Luba2 camera and map

### ISSUE THREAD

**Issue by DBa20-24** [mikey0000/Mammotion-HA#159]
### The problem

It doesn't seem like camera and map of a Luba2 are exposed to HA. Is it on the "feature" list? Or am I just too blind to see?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.46

### What version of Home Assistant Core are you running?

Core-2024.9.1

**Comment by mikey0000** [comment]
Hey, both of those require custom ui elements. Camera also requires you are running home assistant over https. They will come in time.
