### ISSUE TITLE
Yuka Mower Stuck at Grid Start with 'Blade Jammed' Error in Home Assistant

### ISSUE THREAD

**Issue by nieand1985** [mikey0000/Mammotion-HA#163]
### The problem

Hello everyone,

I’m using a Yuka lawn mower and have installed the Mammotion integration in Home Assistant. Both Home Assistant and the integration are up to date. When I start the mower using the configured settings via Home Assistant, it begins to move but then stops at the starting point for grid mowing, and the blades don’t engage. After a while, the error message “Blade jammed” appears, although the blades are free. I’ve tried restarting the Yuka several times, but the issue persists.

My Home Assistant settings:

Mowing: "On/Off"
No-Go Zones: "None"
Obstacle detection mode: "Direct contact"
Navigation mode: "Single grid"
Arena: "Parking lot"
Side grass cutting: "Two patrol rounds"
Rain detection: "Off"
Path distance: "20"
Path angle: "0"
Angle mode: "Relative angle"
Task speed: "0.4"
Path execution order: "Perimeter first"
Starting progress: "0"
Thanks in advance for your support!

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

V0.1.50

### What version of Home Assistant Core are you running?

core-2024.9.3

**Comment by mikey0000** [comment]
at the moment the settings may be a bit off, I've adjusted the blade height default so you should be able to adjust the cut height and even if you don't should default to 25. I've made some changes to mowing which fix some issues, so please retry.

**Comment by nieand1985** [comment]
Hello,
I tried again with v0.1.59 to let the yuka mow a random arena via Home Assistant. There the yuka moves back to the starting point to mow the grid, for example, but there it stops again and the blades are not activated.

After a few minutes, the Mammotion app displays the error: "Blade jammed".

If I want to mow a certain area, I have to do this via the Mammotion app...
pausing and restarting or loading yuka and then restarting works perfectly now.👍🏻

maybe you can help me here too...

Greetings nieand

**Comment by mikey0000** [comment]
I really need a Yuka to test with. I'll see what I can do

**Comment by nieand1985** [comment]
in Home Assistant I can select the 
Activate debug logging and send the logs to you.

When I configure the area with the other settings in the Mammotion app and then start the yuka, it moves to the position, waits there for about 1-2 seconds, then there are several beeps and then the blades activate and it moves along the grid.
In Home Assistant it also moves to position but the beeps don't come at all ... maybe it waits for the command to beep....?!!
it's just an idea of mine

**Comment by mikey0000** [comment]
What I really need is to see what the app sends, I suspect it may exclude the blade height. The code is hard to read so it's difficult.

**Comment by mikey0000** [comment]
try 0.1.65 I managed to check a Yuka command

**Comment by nieand1985** [comment]
Everything works as it should... the yuka now starts the blades and begins to mow !👍🏻

thank you very much for the excellent work

**Comment by nieand1985** [comment]
Hello, a short summary from me: 

After the installation of v0.1.65 the setting of the arena and other settings, as well as the start of the yuka works perfectly 

the yuka now drives to the set area and to the start point of the grid and starts working ( beep sound, blades start running and drive off )

The problem with the grass collecting module has also been fixed. 

The arenas are now also displayed immediately after a restart of Home Assistant

Thanks again for the great work and support

**Comment by mikey0000** [comment]
Awesome to hear!
