### ISSUE TITLE
Problem with Wifi connection

### ISSUE THREAD

**Issue by joerocklin** [mikey0000/Mammotion-HA#164]
### The problem

When trying to configure a wifi connection, the following error repeats without resolution.

```
2024-09-30 20:24:41.095 ERROR (MainThread) [custom_components.mammotion] Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 470, in _async_update_data
    await self.async_send_command("get_device_product_model")
  File "/config/custom_components/mammotion/coordinator.py", line 100, in async_send_command
    await self.manager.send_command_with_args(
  File "/config/deps/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 277, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'command'
```

I'm fairly sure the problem is not in the top-level home assistant module and is buried deep, but I'm starting here hoping to find a resolution.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.50

### What version of Home Assistant Core are you running?

core-2024.9.3

**Comment by mikey0000** [comment]
Its unusual for this to happen, did you start with Bluetooth, then add wifi afterwards?

**Comment by joerocklin** [comment]
@mikey0000 Yes, I had started with bluetooth then tried to add wifi. When that didn't work initially, I removed the integration and then added it again in hopes that would reset things, but it didn't resolve this problem.

**Comment by joerocklin** [comment]
I upgraded the integration, removed the device that had been set up, changed my password (it was ending with a `#` character and I didn't know if that might be contributing to issues), reshared the devices from mammotion's side, then set everything thing back up (with restarts in-between actions) and it all seems to be working without errors now. I'm not sure what specifically in all of that was the problem, but I'm going to close this under the assumption that my local configuration was in a bad state.
