### ISSUE TITLE
HA: 2024.10.0

### ISSUE THREAD

**Issue by jasonmadigan** [mikey0000/Mammotion-HA#168]
### The problem

`Setup failed for custom integration 'mammotion': Requirements for mammotion not found: ['pymammotion==0.2.47'].`

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.42

### What version of Home Assistant Core are you running?

core-2024.10.0

**Comment by jasonmadigan** [comment]
Nevermind, fixed with `v0.1.55`!

**Comment by mikey0000** [comment]
Yeah was going to say 😁
