### ISSUE TITLE
Send mower home to charge using automation?

### ISSUE THREAD

**Issue by TommySharpNZ** [mikey0000/Mammotion-HA#170]
### The problem

I see lots of reviews mention the battery management is very poor and it's common to find your mower dead on the lawn.
With this integration is it possible to force the mower to go back home and charge?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

unsure

### What version of Home Assistant Core are you running?

core-2024.10

**Comment by mikey0000** [comment]
Yes
