### ISSUE TITLE
Disconnecting the application when the module is turned on

### ISSUE THREAD

**Issue by thomasoggier** [mikey0000/Mammotion-HA#174]
### The problem

Every time I activate the hassio mammotion module, the mammotion mobile application disconnects. Not just once, so as to render it unusable.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.69

### What version of Home Assistant Core are you running?

core-2024.10.1

**Comment by mikey0000** [comment]
I know the instructions are perfect but please read them, or suggest improvements, you need to use a seperate account.

**Comment by mikey0000** [comment]
https://github.com/mikey0000/Mammotion-HA/wiki/Getting-Started

**Comment by thomasoggier** [comment]
Sorry this page was not enabled when I download your integration. Just updated it.
So nice module. Thanks
