### ISSUE TITLE
Start Mowing Patrol Laps not working

### ISSUE THREAD

**Issue by Striker2102** [mikey0000/Mammotion-HA#177]
### The problem

Hello,

The start mowing job always sets the Border Patrol laps to one

Border set to none:
![image](https://github.com/user-attachments/assets/5c373c85-d88c-45c4-a6af-3808933ca712)

One Border Patrol lap:
![image](https://github.com/user-attachments/assets/e9150647-88f9-4635-9ec7-b9730331cd78)

Even when I set it to three or four laps, it stays the same.

Thank you.

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.70

### What version of Home Assistant Core are you running?

2024.9.1

**Comment by MCWeid** [comment]
Same on Yuka1500

**Comment by mikey0000** [comment]
Thanks for reporting this, I'll get onto it today

**Comment by mikey0000** [comment]
Fixed in 0.1.72

**Comment by MCWeid** [comment]
Yes it is fixed. Thank you
