### ISSUE TITLE
Back to the charging station?

### ISSUE THREAD

**Issue by Wolfi311** [mikey0000/Mammotion-HA#183]
### The problem

Is there actually the entity back to the charging station yet?
Can't find it

Greetings
Wolfgang

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

V 0.1.70

### What version of Home Assistant Core are you running?

2024.10.3

**Comment by mikey0000** [comment]
Returning state? Or are you talking about the return to charging action? Both exist.

**Comment by Wolfi311** [comment]
What is the difference?
Ok then I have to search again .
What is the name of the entity

**Comment by mikey0000** [comment]
Lawn_mower entity as well as activity mode and device position type

**Comment by mikey0000** [comment]
Hey I'm going to close this as I've not heard back.
