### ISSUE TITLE
Country filter in HACS definition hides it after adding repository

### ISSUE THREAD

**Issue by luke-barnett** [mikey0000/Mammotion-HA#187]
### The problem

Trying to add HACS and have a country filter applied to HACS to filter out any that are not applicable.

I think due to the country specification here: https://github.com/mikey0000/Mammotion-HA/blob/77354993a18242ccdcef3416866ef7e574908a19/hacs.json#L3C1-L3C19 it's being filtered out and so then not visible in the HACS store?

Is there a purpose behind the filter? Other HACS repositories that are global in nature don't have a country specification.

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

unsure

### What version of Home Assistant Core are you running?

core-2024.10.3

**Comment by luke-barnett** [comment]
Awesome, I've created a PR https://github.com/mikey0000/Mammotion-HA/pull/188 to make it easier for you :)

**Comment by mikey0000** [comment]
Ah didn't notice, already pushed the change as I was fixing a few other things.
