### ISSUE TITLE
pymammotion not updated accordingly to info in manifest.json

### ISSUE THREAD

**Issue by rasssta** [mikey0000/Mammotion-HA#192]
### The problem

Not sure if this is a "me problem" or an "integration problem". But I've seen it in the past with this integration as well that pymammotion isn't updated to the required version specified in manifest.json. Any idea what might cause this?

I'm running 0.1.81 and have verified that my manifest.json says:

  "requirements": [
    "pymammotion==0.2.84"
  ]

But my venv is running:
$ pip list | grep mamm
pymammotion                           0.2.76

I have restarted HASS (multiple times) since upgrading to 0.1.81.

I'm running HASS core 2024.8.3. Not sure if there's something special to be done there? Can't recall having this kind of issue with any other integration and I've been running HASS core for 3-4 years. Have I just been lucky or ignorant? :D 

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.1.81

### What version of Home Assistant Core are you running?

2024.8.3

**Comment by mikey0000** [comment]
if that were true the integration wouldn't run at all. Oh also you should check that the base requirement for Mammotion is 2024.9.0 now due to the RETURNING type.

**Comment by rasssta** [comment]
The integration won't load, figured it was due to the login issues I've seen mentioned so I upgraded the integration but still didn't work. Hence why I started to look into this issue. Do you want me to debug anything or should I just upgrade pymammotion manually?

**Comment by mikey0000** [comment]
Have you updated Home assistant to 2024.9.0 or above?

**Comment by saltydog256** [comment]
Same problem.  I am on  2024.10.4. Worked previously.

**Comment by mikey0000** [comment]
Do the logs explicitly say it cannot find the newer versions of pymammotion? If so it's a cache issue with uv / pip and not something I can fix. Usually a reboot or two sorts it.

**Comment by mikey0000** [comment]
UV which home assistant changed to messes up old versions, update to latest
