### ISSUE TITLE
cannot login anymore : Unknown error occurred

### ISSUE THREAD

**Issue by migueldc73** [mikey0000/Mammotion-HA#193]
### The problem

This integration worked for a few weeks. Just got back from business trip and can't login anymore, even when I use a login and pwd of another account (not the one on my phone) and have shared the Luba2 with that account

I removed the integration and when trying to add get the "Unknown error occurred" 

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.77

### What version of Home Assistant Core are you running?

2024.10.4

**Comment by mikey0000** [comment]
Please update to the latest version, if the issue persists re-open this ticket / issue
