### ISSUE TITLE
no_devices_found Luba 2

### ISSUE THREAD

**Issue by SpeijerTom** [mikey0000/Mammotion-HA#25]
All, after trying with the shelly, (which doesn't work, like you guys said) i switched over to a ESP32 board.
I configured it using : https://esphome.io/projects/?type=bluetooth 

I placed the esp32 board at approx 2 meters from my Luba 2
I see it in my unify dashboard that it has internetconnection and is stable. It uses 2.4ghz at channel width 20 channel 11

after a couple HA restarts, i finally got the mammotion integration to show a list of BLE devices it found nearby.
one of them was my Luba, so I selected it.
It was added so i thought it was all good.

However, all values remained at 0 

after giving it some days, and some reboots of both HA and Luba I decided, to start all over again.

removed the bluetoothproxy, 
removed the luba from the mammotion integration, 
redownloaded the mammotion integration
bluetoothproxy esp board was added again
whenever i now go to the mammotion integration and configuring it i get 

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/96daf10e-f4dd-4806-91d8-1c677d397cd2)

any idea what this might be?

**Comment by mikey0000** [comment]
It means it cannot see a Luba, did you add your proxy to home assistant, not just esphome? Also did you flash esp-idf and set it to active Bluetooth?

**Comment by SpeijerTom** [comment]
I have this 

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/ac0591cb-e18f-4362-8129-7864ab0bf01b)

then i get this

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/464c735b-98cd-4435-acde-85912a6663bd)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/15141a7c-0e40-4f0b-9a88-dd98ea05dcbd)

sorry for my perhaps stupid questions, but the bluetooth proxy part is something which is new for me, i've looked at a couple of youtube videos to help me get this going..

**Comment by SpeijerTom** [comment]
> Can you post your esphome code for your proxy?

sorry, not sure what you want here, like i said, i'm too new at this esphome thing.. 
Should I install ESPHome as an add-on on HA?

**Comment by SpeijerTom** [comment]
I used this : https://esphome.io/projects/?type=bluetooth

**Comment by SpeijerTom** [comment]
![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/09af1602-2635-40f7-8988-c66c10c9851b)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/c5be4383-a38e-47dd-9493-10dee30f326c)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/3fe976ff-4c35-4fed-810a-f76dc8dbb3bc)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/d983b440-ae38-439d-bca1-318fca997a69)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/e75e2498-9387-4380-ab78-226c687deb78)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/fef51b67-55af-4c1a-81dc-c51bb5489833)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/7bc9b52b-298a-4f6c-b3fe-efdc61bb0008)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/259bcb57-de7d-4286-8360-44b2d113e6a9)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/f28d7634-ca51-4b7f-8f1b-7ed4daccf32f)

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/1a7013a6-8b75-4085-92b0-5394b759dae1)

I flashed it again, perhaps something went wrong, I will go outside now to place it near Luba again
(currently it's mowing, near the spot, does it work when it's mowing, or should I wait until it's in the dock?)

**Comment by SpeijerTom** [comment]
After reconfiguring the esp board, i managed to get it added again.
However, now the same "issue" occurs, which are the 0 values for everything.
Should I close this issue and open another, or what do you like?

![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/75c960aa-a1c7-45d8-8e67-a7b13d23cec0)

btw thank you for the effort and support, you guys are legends!

**Comment by SpeijerTom** [comment]
not sure if related, but this is want i noticed
![image](https://github.com/mikey0000/Mammotion-HA/assets/170707733/a5a40cb1-f890-461c-8ef6-8ca9153ae4f2)

**Comment by mikey0000** [comment]
Can you pull the integration from HACS again and try again.

**Comment by SpeijerTom** [comment]
> If you join our discord (link on the home page) it might be easier there to help you out as I have another idea that might work

I've been trying to get a discord account created, tried already with 2 e-mailaddresses, activated the link (which i got from my mailbox), but when i try to login, it says account doesn't exist.
I've asked Discord a question through support on X

Will keep you updated

**Comment by mikey0000** [comment]
Can you re-pull the integration and try again, we have other users of Luba 2 where its working fine, so best join Discord and we can help you with your setup, closing as others have reported it working, so is likely a bluetooth issue.
