### ISSUE TITLE
Luba status - Returning to the charging station

### ISSUE THREAD

**Issue by veshapidze** [mikey0000/Mammotion-HA#46]
### The problem

I am trying to get the following states as reported by notifications:
The task has started
The task has continued
Returning to the charging station

is it even possible?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

latest

### What version of Home Assistant Core are you running?

Latest

**Comment by mikey0000** [comment]
Yes possible, over either Bluetooth or WiFi, some patience required while we are busy working towards these things.

**Comment by mikey0000** [comment]
Hey I've exposed an activity state sensor, you should be able to use this for your purposes

**Comment by mikey0000** [comment]
Exposed entity Activity Mode which should suite your needs

**Comment by veshapidze** [comment]
That’s awesome. Thank you!
