### ISSUE TITLE
Failed Setup

### ISSUE THREAD

**Issue by mdp716** [mikey0000/Mammotion-HA#51]
### The problem

Not really a problem as I resolved it, but wanted to share.

Went to set up a new Yuka mower and when adding the integration it found the Yuka by name but then errored out with a "Invalid Flow Specified" message.

Closing everything out and trying again the mower was now populated but again failed when I went to set it up.  Rebooting the HA server followed by trying to set up the integration removed the Yuka Device but when trying to add it back it was no longer visible in the list of devices that can be selected.

I discovered that the Yuka was not appearing in my cell phone either (I had the mammotion app closed).  After powering off and then restarting the Mower, the BT instance reappeared and I was then able to set it up in HA.

Oh, and BTW, thank you so much for your time and expertise in creating this integration.

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.0.4

### What version of Home Assistant Core are you running?

core-2024.7.4

**Comment by mikey0000** [comment]
Pretty sure this is now resolved in 0.0.12
