### ISSUE TITLE
v0.0.19 "Failed Setup" Error when devices is added.

### ISSUE THREAD

**Issue by lackr007** [mikey0000/Mammotion-HA#65]
### The problem

After deleting device, then redownloading v0.0.19, rebooting, then attempting to add device it errors out. See below.

![image](https://github.com/user-attachments/assets/f2fa3bd7-d6e4-448a-bbfa-dd4f1bca369d)

This error originated from a custom integration.

Logger: custom_components.mammotion
Source: helpers/update_coordinator.py:354
integration: Mammotion
First occurred: 5:30:21 PM (12 occurrences)
Last logged: 5:35:37 PM

Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 111, in _async_update_data
    if self.device.luba_msg.device.sys.toapp_report_data.dev.sys_status != WorkMode.MODE_WORKING:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'toapp_report_data'

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.0.19

### What version of Home Assistant Core are you running?

core- 2024.8.1

**Comment by mikey0000** [comment]
Can you redownload it? Otherwise I'm working on a better fix for this issue.

**Comment by mikey0000** [comment]
Can you try 0.0.20 please

**Comment by lackr007** [comment]
v 0.0.22 fixes this issue, however there are some different issues discovered with this version. I will open/start another issue....
