### ISSUE TITLE
Added Italian translation

### ISSUE THREAD

**Issue by Subia75** [mikey0000/Mammotion-HA#70]
### The problem

Hi
I have no idea how to attach files on github, so I'm asking where I can send the file.
I haven't bought my luba 2 yet because I can't find the model available, but I've been following the project since the beginning and I wanted to contribute with the translation for my language.
As soon as I can get it I hope to be able to contribute with something else?

thanks

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

none yet

### What version of Home Assistant Core are you running?

core-2024.8.2

**Comment by mikey0000** [comment]
Hey that's awesome, I'd suggest jumping on discord and sending to me/us there.
