### ISSUE TITLE
Not sure if this is a new issue? Wont Set up 

### ISSUE THREAD

**Issue by kilrgt** [mikey0000/Mammotion-HA#85]
### The problem

Hi all, been testing this since almost day one, I never really had a bluetooth network set up so i was just connected randomly when it was close enough to my Pie, now thats its wifi, i created a secondary account so i can use the app and the integration. Im getting some errors, again not sure if this is not new or not, i did try with the main account and same results. Its connected to the same network and i can see it online via the app. So if its a issue on my end i apologize, i know you're working hard on this 

logs

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 7:23:40 AM (1 occurrences)
Last logged: 7:23:40 AM

Error setting up entry Luba for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 89, in async_setup
    self.manager = await create_devices(ble_device, credentials, preference)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 204, in create_devices
    cloud_client = await Mammotion.login(cloud_credentials.account_id or cloud_credentials.email,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 272, in login
    await cloud_client.login_by_oauth(country_code, mammotion_http.login_info.authorization_code)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 383, in login_by_oauth
    raise LoginException(data)
pymammotion.aliyun.cloud_gateway.LoginException: {'timestamp': 1724844220374, 'status': 400, 'error': 'Bad Request', 'exception': 'org.springframework.web.bind.MissingServletRequestParameterException', 'message': "Required String parameter 'loginByOauthRequest' is not present", 'path': '/account/api/loginbyoauth.json'}

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.3

### What version of Home Assistant Core are you running?

	core-2024.8.3

**Comment by MiddleSiggy** [comment]
Just updated, and have the same issue:

{'timestamp': 1724870293663, 'status': 400, 'error': 'Bad Request', 'exception': 'org.springframework.web.bind.MissingServletRequestParameterException', 'message': "Required String parameter 'loginByOauthRequest' is not present", 'path': '/account/api/loginbyoauth.json'}

**Comment by mikey0000** [comment]
Fix coming right now for that.

**Comment by MiddleSiggy** [comment]
The latest change fixed it.. I can confirm it is now working, and updating as expected
