### ISSUE TITLE
Feature Request - Add Last Updated Element

### ISSUE THREAD

**Issue by MiddleSiggy** [mikey0000/Mammotion-HA#87]
### The problem

Feature Request:
- It would be nice to have a last updated element for HA, given the mowers can move outside the WiFi or BlueTooth area it would be nice to see when the last update came through.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

Current

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mong00se007** [comment]
if you click on the car icon it says when it last updated.
you can also click on the icon in the map to get to the same point.
If you want to see last place it was. you can install this card https://github.com/nathan-gs/ha-map-card in hacs. you can then have markers with timestamps when you hover your mouse above it. to see where it was when.

**Comment by mikey0000** [comment]
Closing as resolved.
