### ISSUE TITLE
Argument for pymammotion.http.http.LoginResponseData.__mashumaro_from_dict__ method should be a dict instance

### ISSUE THREAD

**Issue by liblit** [mikey0000/Mammotion-HA#88]
### The problem

While adding this integration, I provided the mower name, Mammotion email, and Mammotion account password as prompted, then clicked SUBMIT. I then saw an error overlay reporting:

> Argument for pymammotion.http.http.LoginResponseData.__mashumaro_from_dict__ method should be a dict instance

The integration was ultimately not added.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.5

### What version of Home Assistant Core are you running?

core-2024.8.2

**Comment by mikey0000** [comment]
Hi problem is your user and password

**Comment by mikey0000** [comment]
Error needs to be caught and displayed better I know. Getting there

**Comment by liblit** [comment]
I originally used my Google account to sign up with Mammotion. Apparently that doesn't really associate my Google email address with my Mammotion password. When I provided my numeric Mammotion account ID and and Mammotion password instead, that worked. Yay! 🥳

Thanks for the helpful clue, and for this project in general.

**Comment by mikey0000** [comment]
Oh good to know.

**Comment by mikey0000** [comment]
Errors properly show now.
