### ISSUE TITLE
Exclusive access to LUBA

### ISSUE THREAD

**Issue by sgurgul** [mikey0000/Mammotion-HA#89]
### The problem

It seems like the integration is taking over connection with LUBA device so the Mammotion (phone) app is logged out automatically.

Is it something could be improved in the future ? Or rather a known limitation of the Mammotion device that it cannot keep connections to two different clients concurrently ?

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.4

### What version of Home Assistant Core are you running?

2024.8.3

**Comment by ThorstenBoettler** [comment]
you can only be logged in with one "device" to the account, all other devices are logged out. 
You can create a second mammotion account and share your Luba to that account. then you can use this new account for HA and your main-account will stay logged in.

**Comment by mikey0000** [comment]
Won't and can't fix. You need to use a second account and share to it as @ThorstenBoettler said.

**Comment by sgurgul** [comment]
OK, all clear. Thank you.
