### ISSUE TITLE
Please Add Polish Language Support for Mammotion Mower

### ISSUE THREAD

**Issue by manguscik** [mikey0000/Mammotion-HA#91]
### The problem

I would like to add a Polish translation for Mammotion - Home Assistant Integration. I was not able to do it via pull requests so I will add it here.

Description
I introduce a comprehensive Polish translation for the Mammotion component.

Translations cover configuration messages, sensor states and device actions.

Aimed at improving accessibility for Polish user.

[pl.json](https://github.com/user-attachments/files/16800868/pl.json)

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

V0.1.6

### What version of Home Assistant Core are you running?

2024.8.3

**Comment by mikey0000** [comment]
Done, thank you for your contribution!
