### ISSUE TITLE
Integration does not start because of NL translation issue

### ISSUE THREAD

**Issue by bdormael** [mikey0000/Mammotion-HA#92]
### The problem

When upgrading to version 0.1.6 I cannot start the integration anymore, it gives an error as shown in the screenshot below:
![IMG_3733](https://github.com/user-attachments/assets/31b0e699-211d-412d-87d6-5b978315dcbc)

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

unsure

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by driesvandamme** [comment]
https://github.com/mikey0000/Mammotion-HA/pull/93

Correction proposed

**Comment by mikey0000** [comment]
Thanks
