### ISSUE TITLE
Add notifications/events for „rain started“

### ISSUE THREAD

**Issue by thallth** [mikey0000/Mammotion-HA#94]
### The problem

My main puropose for this HomaAssistant plugin was to start the mower again, after rain started (after weather service sais „rain ended“ for 1h)

But the only thing I can find to use in an automation regarding rain, is the setting (mow on rainy days) itself?

Please add a sensor/trigger for the actual rain detection.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.4

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
If only the robot actually reported this, sorry the mammotion lawn mowers do not report the status of the rain sensor. I suggest using a weather service or getting an additional rain sensor.

**Comment by thallth** [comment]
Are you in contact with devs from Mammotion so that it will be added in future?

I know that I can use every other service/sensor, but I would prefer using the information and status from the robot itself.

**Comment by mikey0000** [comment]
> Are you in contact with devs from Mammotion so that it will be added in future?
> 
> I know that I can use every other service/sensor, but I would prefer using the information and status from the robot itself.

Yes I am, I can request / ask, no promises. Alternatively there is likely an event over MQTT when it detects rain, I can almost guarantee it. I'll check.
